Repository glue-viz/glue-plotly, pull requests merged in 2022-10, with the labels that each got.

#21 Setup automated changelog generation for release process
  .github/release.yml
  .github/workflows/ci_workflows.yml
  .github/workflows/update-changelog.yaml
  CHANGES.md
  CHANGES.rst
  README.rst
  RELEASE.rst
Labels: enhancement, no-changelog-entry-needed

#22 DOC: update order of autogenerated Changelog entries
  .github/release.yml
  README.rst
Labels: no-changelog-entry-needed

#20 Add exporter for histogram viewer
  glue_plotly/__init__.py
  glue_plotly/html_exporters/__init__.py
  glue_plotly/html_exporters/histogram.py
  glue_plotly/html_exporters/tests/test_histogram.py
Labels: enhancement
